apiVersion: 1

datasources:
  - name: MySQL
    type: mysql
    access: proxy
    url: db:3306
    database: wifi_auth
    user: dbuser
    password: dbpass
    jsonData:
      maxOpenConns: 10
      maxIdleConns: 5
      connMaxLifetime: 14400

dashboards:
  - name: WiFi Auth Dashboard
    options:
      path: /etc/grafana/provisioning/dashboards