version: '3.8'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    environment:
      - DATABASE_URL=mysql://dbuser:dbpass@db/wifi_auth
      - SECRET_KEY=your-secret-key
    depends_on:
      - db
      - grafana

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: wifi_auth
      MYSQL_USER: dbuser
      MYSQL_PASSWORD: dbpass
    volumes:
      - db_data:/var/lib/mysql

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning
      - grafana_data:/var/lib/grafana

volumes:
  db_data:
  grafana_data: